import React, { useState } from 'react';
import { Share2, Check, Copy } from 'lucide-react';

/**
 * ShareButton — Generates a clean text summary of scan results and shares via
 * Web Share API (native share sheet on mobile) or copies to clipboard on desktop.
 * Fully isolated — does NOT modify any existing component.
 */
export default function ShareButton({ data, language = 'en' }) {
  const [copied, setCopied] = useState(false);
  const hi = language === 'hi';

  if (!data || !data.medicines?.length) return null;

  const generateSummary = () => {
    const lines = [];
    
    lines.push(hi ? '━━━ MedMitra विश्लेषण ━━━' : '━━━ MedMitra Analysis ━━━');
    lines.push('');

    if (data.patientName) {
      lines.push(`${hi ? 'मरीज' : 'Patient'}: ${data.patientName}`);
    }
    lines.push(`${hi ? 'प्रकार' : 'Type'}: ${data.documentType === 'prescription' ? (hi ? 'प्रिस्क्रिप्शन' : 'Prescription') : (hi ? 'लेबल' : 'Label')}`);
    lines.push('');

    data.medicines.forEach((med, i) => {
      lines.push(`💊 ${hi ? 'दवा' : 'Medicine'} ${i + 1}: ${med.name}`);
      if (med.genericName && med.genericName !== med.name) {
        lines.push(`   ${hi ? 'जेनेरिक' : 'Generic'}: ${med.genericName}`);
      }
      lines.push(`   ${hi ? 'उपयोग' : 'Usage'}: ${med.usage}`);
      lines.push(`   ${hi ? 'खुराक' : 'Dosage'}: ${med.dosage}`);
      lines.push(`   ${hi ? 'कब लें' : 'When'}: ${med.instructions}`);
      if (med.sideEffects) {
        lines.push(`   ⚠️ ${hi ? 'दुष्प्रभाव' : 'Side effects'}: ${med.sideEffects}`);
      }
      lines.push('');
    });

    if (data.actionableInstructions) {
      lines.push(`📋 ${hi ? 'निर्देश' : 'Summary'}: ${data.actionableInstructions}`);
      lines.push('');
    }

    lines.push(hi ? '⚕️ कृपया डॉक्टर की सलाह अवश्य लें।' : '⚕️ Always consult your doctor.');
    lines.push('');
    lines.push(hi ? '🔗 MedMitra से बनाया गया' : '🔗 Generated by MedMitra');

    return lines.join('\n');
  };

  const handleShare = async () => {
    const text = generateSummary();

    // Try native Web Share API first (mobile)
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'MedMitra — Medicine Analysis',
          text,
        });
        return;
      } catch (err) {
        // User cancelled or API failed — fall through to clipboard
        if (err.name === 'AbortError') return;
      }
    }

    // Fallback: copy to clipboard
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Last resort: textarea trick
      const textarea = document.createElement('textarea');
      textarea.value = text;
      textarea.style.position = 'fixed';
      textarea.style.opacity = '0';
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <button
      className={`share-btn ${copied ? 'copied' : ''}`}
      onClick={handleShare}
      title={hi ? 'शेयर करें' : 'Share results'}
    >
      {copied ? (
        <>
          <Check size={16} />
          <span>{hi ? 'कॉपी हो गया!' : 'Copied!'}</span>
        </>
      ) : (
        <>
          <Share2 size={16} />
          <span>{hi ? 'शेयर करें' : 'Share'}</span>
        </>
      )}
    </button>
  );
}
